apiVersion: apps/v1
kind: Deployment
metadata:
  name: bz-f8t-registr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bz-f8t-registr
  template:
    metadata:
      labels:
        app: bz-f8t-registr
    spec:
      containers:
      - name: bz-f8t-registr
        image: crf8tdevwesteu.azurecr.io/bz-f8t-registr:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__Postgres
          value: "$DB_REGISTR_CONNSTR"
        - name: ConnectionStrings__AzureServiceBus
          value: "$SERVICE_BUS_CONNSTR"
        - name: ConnectionStrings__ApplicationInsights
          value: "$APP_INSIGHTS_CONNSTR"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - bz-f8t-registr
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: bz-f8t-registr-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: bz-f8t-registr